config/routes.rb
Inventory::Application.routes.draw do
  get "welcome/index"

  resources :locations

  resources :resources

  root :to => 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :name
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, :notice => 'Location was successfully created.' }
        format.json { render :json => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, :notice => 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @resources }
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
    @resource = Resource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @resource }
    end
  end

  # GET /resources/new
  # GET /resources/new.json
  def new
    @resource = Resource.new
    @locations = Location.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @resource }
    end
  end

  # GET /resources/1/edit
  def edit
    @resource = Resource.find(params[:id])
    @locations = Location.all
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(params[:resource])

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, :notice => 'Resource was successfully created.' }
        format.json { render :json => @resource, :status => :created, :location => @resource }
      else
        format.html { render :action => "new" }
        format.json { render :json => @resource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /resources/1
  # PUT /resources/1.json
  def update
    @resource = Resource.find(params[:id])

    respond_to do |format|
      if @resource.update_attributes(params[:resource])
        format.html { redirect_to @resource, :notice => 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @resource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.address %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>
<%= link_to 'Back to Welcome', welcome_index_path %>
<%= link_to 'Resources', resources_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_type %><br />
    <%= f.text_field :resource_type %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :purchased_at %><br />
    <%= f.date_select :purchased_at %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.select (:location_id, @locations.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :user_names %><br />
    <%= f.text_field :user_names %>
  </div>
  <div class="field">
    <%= f.label :salvage %><br />
    <%= f.text_field :salvage %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit "Add This Resource", :class => "button" %>
  </div>
<% end %>

app/views/resources/index.html.erb
<h1>Here is a Listing of your resources</h1>

<table>
  <tr>
    <th>Resource type</th>
    <th>Make</th>
    <th>Model</th>
    <th>.....Purchased on.....</th>
    <th>Serial number</th>
    <th>Location</th>
    <th>User names</th>
    <th>Salvage</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.resource_type %></td>
    <td><%= resource.make %></td>
    <td><%= resource.model %></td>
    <td><%= resource.purchased_at.strftime("%m/%d/%Y") %></td>
    <td><%= resource.serial_number %></td>
    <td><%= resource.location_id %></td>
    <td><%= resource.user_names %></td>
    <td><%= resource.salvage %></td>
    <td><%= resource.value %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add resource', new_resource_path, :class => "button" %>
<%= link_to 'Add location', new_location_path, :class => "button" %>

app/views/welcome/index.html.erb
<h1>The Resources Locator</h1>
<p>The Resources Locator (TRL) is a friendly tool you can use to remember where resources are located.  To view or add a resource or location click below.
<p>
<%= link_to 'Resources', resources_path %>
<%= link_to 'Locations', locations_path %>